# **Bioinformatics Project - Computational Drug Discovery [Part 1] Download Bioactivity Data (Concised version)**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 1**, we will be performing Data Collection and Pre-Processing from the ChEMBL Database.

Note for this Concised Version:
* Redundant code cells were deleted.
* Code cells for saving files to Google Drive has been deleted.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (0.10.9)
Requirement already satisfied: urllib3 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from chembl_webresource_client) (2.32.5)
Requirement already satisfied: requests-cache~=1.2 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from chembl_webresource_client) (1.3.1)
Requirement already satisfied: easydict in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: attrs>=21.2 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.0)
Requirement already satisfied: url-normalize>=2.0 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (2.2.1)
Requirement already satisfied: typing-extensions>=4.14.0 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\orippee\appdata\local\anaconda3\lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (2025.11.12)

## **Importing libraries**

In [2]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

C:\Users\ORippee\AppData\Local\anaconda3\Lib\site-packages\chembl_webresource_client\__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

## **Search for Target protein**

### **Target search for Acetylcholinesterase**

In [ ]:
# Target search for coronavirus
target = new_client.target
target_query = target.search('acetylcholinesterase')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Drosophila melanogaster,Acetylcholinesterase,18.0,False,CHEMBL2242744,"[{'accession': 'P07140', 'component_descriptio...",SINGLE PROTEIN,7227
1,[],Homo sapiens,Acetylcholinesterase,16.0,False,CHEMBL220,"[{'accession': 'P22303', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Torpedo californica,Acetylcholinesterase,16.0,False,CHEMBL4780,"[{'accession': 'P04058', 'component_descriptio...",SINGLE PROTEIN,7787
3,[],Mus musculus,Acetylcholinesterase,16.0,False,CHEMBL3198,"[{'accession': 'P21836', 'component_descriptio...",SINGLE PROTEIN,10090
4,[],Rattus norvegicus,Acetylcholinesterase,16.0,False,CHEMBL3199,"[{'accession': 'P37136', 'component_descriptio...",SINGLE PROTEIN,10116
5,[],Electrophorus electricus,Acetylcholinesterase,16.0,False,CHEMBL4078,"[{'accession': 'O42275', 'component_descriptio...",SINGLE PROTEIN,8005
6,[],Bos taurus,Acetylcholinesterase,16.0,False,CHEMBL4768,"[{'accession': 'P23795', 'component_descriptio...",SINGLE PROTEIN,9913
7,[],Anopheles gambiae,Acetylcholinesterase,16.0,False,CHEMBL2046266,"[{'accession': 'Q869C3', 'component_descriptio...",SINGLE PROTEIN,7165
8,[],Bemisia tabaci,AChE2,16.0,False,CHEMBL2366409,"[{'accession': 'B3SST5', 'component_descriptio...",SINGLE PROTEIN,7038
9,[],Leptinotarsa decemlineata,Acetylcholinesterase,16.0,False,CHEMBL2366490,"[{'accession': 'Q27677', 'component_descriptio...",SINGLE PROTEIN,7539
10,[],Nephotettix cincticeps,Ace-orthologous acetylcholinesterase,16.0,False,CHEMBL2366514,"[{'accession': 'Q9NJH6', 'component_descriptio...",SINGLE PROTEIN,94400
11,[],Gallus gallus,Acetylcholinesterase,16.0,False,CHEMBL3227914,"[{'accession': 'P36196', 'component_descriptio...",SINGLE PROTEIN,9031
12,[],Danio rerio,Acetylcholinesterase,16.0,False,CHEMBL3308995,"[{'accession': 'Q9DDE3', 'component_descriptio...",SINGLE PROTEIN,7955
13,[],Aedes aegypti,Acetylcholinesterase,16.0,False,CHEMBL4295607,"[{'accession': 'Q6A2E2', 'component_descriptio...",SINGLE PROTEIN,7159
14,[],Homo sapiens,Protein CutA,16.0,False,CHEMBL6067022,"[{'accession': 'O60888', 'component_descriptio...",SINGLE PROTEIN,9606
15,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL5752,"[{'accession': 'Q95P20', 'component_descriptio...",SINGLE PROTEIN,7370
16,[],Plutella xylostella,Acetylcholinesterase,15.0,False,CHEMBL2242729,"[{'accession': 'Q8MZM0', 'component_descriptio...",SINGLE PROTEIN,51655
17,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL2242743,"[{'accession': 'Q7YWJ9', 'component_descriptio...",SINGLE PROTEIN,7370
18,[],Pediculus humanus capitis,Acetylcholinesterase,15.0,False,CHEMBL2362988,"[{'accession': 'A2PZ98', 'component_descriptio...",SINGLE PROTEIN,121226
19,[],Spodoptera litura,Acetylcholinesterase,15.0,False,CHEMBL2366422,"[{'accession': 'C5IU80', 'component_descriptio...",SINGLE PROTEIN,69820
20,[],Laodelphax striatella,Acetylcholinesterase,15.0,False,CHEMBL2366446,"[{'accession': 'K4JQ36', 'component_descriptio...",SINGLE PROTEIN,195883
21,[],Schizaphis graminum,Acetylcholinesterase,15.0,False,CHEMBL2366511,"[{'accession': 'Q9BMJ1', 'component_descriptio...",SINGLE PROTEIN,13262
22,[],Homo sapiens,Cholinesterases; ACHE & BCHE,14.0,False,CHEMBL2095233,"[{'accession': 'P06276', 'component_descriptio...",SELECTIVITY GROUP,9606
23,[],Rattus norvegicus,Acetylcholinesterase and butyrylcholinesterase...,14.0,False,CHEMBL2111475,"[{'accession': 'P37136', 'component_descriptio...",SELECTIVITY GROUP,10116
24,[],Caenorhabditis elegans,Acetylcholinesterase 1,14.0,False,CHEMBL3341583,"[{'accession': 'P38433', 'component_descriptio...",SINGLE PROTEIN,6239
25,[],Equus caballus,Butyrylcholinesterase,11.0,False,CHEMBL5077,"[{'accession': 'Q9N1N9', 'component_descriptio...",SINGLE PROTEIN,9796
26,[],Equus caballus,Cholinesterase,11.0,False,CHEMBL5763,"[{'accession': 'P81908', 'component_descriptio...",SINGLE PROTEIN,9796
27,[],Canis lupus familiaris,Cholinesterase,11.0,False,CHEMBL4630814,"[{'accession': 'P32750', 'component_descriptio...",SINGLE PROTEIN,9615
28,[],Mus musculus,Cholinesterase,10.0,False,CHEMBL2528,"[{'accession': 'Q03311', 'component_descriptio...",SINGLE PROTEIN,10090
29,[],Rattus norvegicus,Butyrylcholinesterase,10.0,False,CHEMBL3403,"[{'accession': 'Q9JKC1', 'component_descriptio...",SINGLE PROTEIN,10116
30,[],Homo sapiens,Cholinesterase,5.0,False,CHEMBL1914,"[{'accession': 'P06276', 'component_descriptio...",SINGLE PROTEIN,9606

### **Select and retrieve bioactivity data for *Human Acetylcholinesterase* (first entry)**

We will assign the fifth entry (which corresponds to the target protein, *Human Acetylcholinesterase*) to the ***selected_target*** variable

In [ ]:
selected_target = targets.target_chembl_id[5]
selected_target

'CHEMBL4078'

Here, we will retrieve only bioactivity data for *Human Acetylcholinesterase* (CHEMBL220) that are reported as pChEMBL values.

In [ ]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [13]:
df = pd.DataFrame.from_dict(res)

KeyboardInterrupt:

In [ ]:
df

     activity_comment  activity_id  ... upper_value value
0                None        33969  ...        None  0.75
1                None        37563  ...        None   0.1
2                None        37565  ...        None  50.0
3                None        38902  ...        None   0.3
4                None        41170  ...        None   0.8
...               ...          ...  ...         ...   ...
7021             None     18798886  ...        None  3.81
7022             None     18798887  ...        None  3.46
7023             None     18798888  ...        None  2.78
7024             None     18798889  ...        None  0.45
7025             None     18798890  ...        None  2.51

[7026 rows x 43 columns]

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [14]:
df.to_csv('acetylcholinesterase_01_bioactivity_data_raw.csv', index=False)

NameError: name 'df' is not defined

## **Handling missing data**
If any compounds has missing value for the **standard_value** and **canonical_smiles** column then drop it.

In [16]:
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

NameError: name 'df' is not defined

In [ ]:
len(df2.canonical_smiles.unique())

4695

In [ ]:
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

     activity_comment  activity_id  ... upper_value value
0                None        33969  ...        None  0.75
1                None        37563  ...        None   0.1
2                None        37565  ...        None  50.0
3                None        38902  ...        None   0.3
4                None        41170  ...        None   0.8
...               ...          ...  ...         ...   ...
7019             None     18798884  ...        None  2.44
7020             None     18798885  ...        None  2.54
7021             None     18798886  ...        None  3.81
7022             None     18798887  ...        None  3.46
7023             None     18798888  ...        None  2.78

[4695 rows x 43 columns]

## **Data pre-processing of the bioactivity data**

### **Combine the 3 columns (molecule_chembl_id,canonical_smiles,standard_value) and bioactivity_class into a DataFrame**

In [ ]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

     molecule_chembl_id  ... standard_value
0          CHEMBL133897  ...          750.0
1          CHEMBL336398  ...          100.0
2          CHEMBL131588  ...        50000.0
3          CHEMBL130628  ...          300.0
4          CHEMBL130478  ...          800.0
...                 ...  ...            ...
7019      CHEMBL4293155  ...         2440.0
7020      CHEMBL4282558  ...         2540.0
7021      CHEMBL4281727  ...         3810.0
7022      CHEMBL4292349  ...         3460.0
7023      CHEMBL4278260  ...         2780.0

[4695 rows x 3 columns]

Saves dataframe to CSV file

In [ ]:
df3.to_csv('acetylcholinesterase_02_bioactivity_data_preprocessed.csv', index=False)

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [ ]:
df4 = pd.read_csv('acetylcholinesterase_02_bioactivity_data_preprocessed.csv')

In [ ]:
bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")

In [ ]:
bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

     molecule_chembl_id  ...         class
0          CHEMBL133897  ...        active
1          CHEMBL336398  ...        active
2          CHEMBL131588  ...      inactive
3          CHEMBL130628  ...        active
4          CHEMBL130478  ...        active
...                 ...  ...           ...
4690      CHEMBL4293155  ...  intermediate
4691      CHEMBL4282558  ...  intermediate
4692      CHEMBL4281727  ...  intermediate
4693      CHEMBL4292349  ...  intermediate
4694      CHEMBL4278260  ...  intermediate

[4695 rows x 4 columns]

Saves dataframe to CSV file

In [ ]:
df5.to_csv('acetylcholinesterase_03_bioactivity_data_curated.csv', index=False)

In [ ]:
! zip acetylcholinesterase.zip *.csv

  adding: acetylcholinesterase_01_bioactivity_data_raw.csv (deflated 90%)
  adding: acetylcholinesterase_02_bioactivity_data_preprocessed.csv (deflated 81%)
  adding: acetylcholinesterase_03_bioactivity_data_curated.csv (deflated 82%)

In [ ]:
! ls -l

total 4668
-rw-r--r-- 1 root root 3562870 Jun  1 15:03 acetylcholinesterase_01_bioactivity_data_raw.csv
-rw-r--r-- 1 root root  342989 Jun  1 15:03 acetylcholinesterase_02_bioactivity_data_preprocessed.csv
-rw-r--r-- 1 root root  385924 Jun  1 15:03 acetylcholinesterase_03_bioactivity_data_curated.csv
-rw-r--r-- 1 root root  475843 Jun  1 15:03 acetylcholinesterase.zip
drwxr-xr-x 1 root root    4096 May 27 16:27 sample_data

---